import type { ComplianceReport } from "./types"

export const mockReportData: ComplianceReport = {
  status: "success",
  message: "Success",
  code: "SUCCESS",
  data: {
    id: "45e38d43-952d-4c6d-8a67-01417c979a52",
    employee_type: "new_employee",
    verification_status: "fully_compliant",
    is_employment_reviewed: true,
    employment_reviewed_by: "Safer Recruit",
    employment_reviewed_at: "24/10/2025 07:11PM",
    konfir_verification_id: "241161b2-2391-4550-85fa-e5e0feceb334",
    checks: [
      {
        name: "identity_verification",
        description:
          "Ensure that candidates are who they claim to be, enhancing trust and safety by preventing fraudulent or false identities.",
      },
      {
        name: "dbs_check",
        description:
          "Verifies criminal history to ensure the applicant has no offenses that would disqualify them from working with vulnerable individuals, especially children.",
      },
      {
        name: "health_check",
        description:
          "Ensure the candidate is physically fit and free from any health conditions that could impact their ability to perform the job.",
      },
    ],
    is_employment_history_verified: true,
    package: null,
    todo_items: [
      { task_type: "identity_verification", status: "completed" },
      { task_type: "health_check", status: "completed" },
      { task_type: "dbs_check", status: "completed" },
      { task_type: "references", status: "completed" },
      { task_type: "document_upload", status: "completed" },
    ],
    care_home: {
      id: "0be808b5-7c10-46b2-adae-33155d78d60e",
      name: "Safer Recruit Demo",
      address: "",
      regulatory_body: "",
      care_home_type: "",
      website: "",
      services_offered: "",
    },
    profile: {
      user_full_name: "Brian Margret",
      email: "nathzzy03+008@gmail.com",
      full_address: "14 Gotham Street, London, GB, SW1A 0AA",
      phone: "+447745111255",
    },
    cv: {
      id: "5756a069-5099-41e5-9869-a3a895d28f05",
      file: "Nathaniel_Resume.pdf",
      file_size: 99051,
      url: "https://safer-recruit.s3.amazonaws.com/uploads/employee_cvs/a9ebc29f-b0a2-49c1-93ba-ec6834627f2c/Nathaniel_Resume.pdf",
    },
    supporting_documents: [
      {
        id: "6195175b-c04e-4ef3-9f70-614b94ad8b66",
        document: "Nathaniel_Resume.pdf",
        document_type: "qualification_evidence",
        document_size: 99051,
        description: "",
        is_reviewed: true,
        reviewed_by: "Safer Recruit",
        reviewed_at: "24/10/2025 07:11PM",
        file_url:
          "https://safer-recruit.s3.amazonaws.com/uploads/employee_cvs/a9ebc29f-b0a2-49c1-93ba-ec6834627f2c/Nathaniel_Resume.pdf",
      },
      {
        id: "40ff2e1d-6bce-4608-a52b-73b252c4ff3e",
        document: "Welcome.pdf",
        document_type: "qualification_evidence",
        document_size: 142718,
        description: "",
        is_reviewed: true,
        reviewed_by: "Safer Recruit",
        reviewed_at: "24/10/2025 07:11PM",
        file_url: "https://safer-recruit.s3.amazonaws.com/uploads/documents/Welcome.pdf",
      },
      {
        id: "994c2bd9-b85b-492c-923c-eb5b3b6188c2",
        document: "Health_Declaration.pdf",
        document_type: "health_document",
        document_size: 142718,
        description: "",
        is_reviewed: true,
        reviewed_by: "Safer Recruit",
        reviewed_at: "24/10/2025 07:11PM",
        file_url: "https://safer-recruit.s3.amazonaws.com/uploads/documents/Health_Declaration.pdf",
      },
    ],
    employment_histories: [
      {
        id: "eebfa8ee-847b-4fee-9b95-8a3a92cf26dc",
        company_name: "acme ltd.",
        start_date: "2021-01-01",
        end_date: null,
        gap_explanation: "",
        role: "Manager",
        is_declared: false,
        is_current: false,
        verification_status: "verified",
        alerts: [],
        insights: [],
      },
      {
        id: "6d202ae4-246b-4a89-80e1-b617d69db8b4",
        company_name: "test employer",
        start_date: "1999-01-19",
        end_date: null,
        gap_explanation: "",
        role: "Lead",
        is_declared: false,
        is_current: false,
        verification_status: "verified",
        alerts: [],
        insights: [],
      },
      {
        id: "ed55613f-ac34-49c3-8688-0fb3d41b1d95",
        company_name: "Pluralcode Academy",
        start_date: "2022-11-01",
        end_date: "2025-10-01",
        gap_explanation: "",
        role: "Lead",
        is_declared: true,
        is_current: false,
        verification_status: "not_verified",
        alerts: [],
        insights: [],
      },
    ],
    references: [
      {
        id: "8434a3d6-ff1d-47c7-8de7-654627c11405",
        is_for_latest_employment: false,
        referee_name: "Gustin",
        company_name: "test employer",
        referee_role: "Lead",
        referee_email: "gus@gmail.com",
        reference_type: "professional_reference",
        referee_phone_number: "+447744412555",
        is_reviewed: true,
        reviewed_by: "Safer Recruit",
        reviewed_at: "24/10/2025 07:11PM",
        reference_entry: {
          id: "d519c7db-70d6-446e-8c30-087b2a0b00e5",
          date_received: "24/10/2025 08:03AM",
          notes:
            "I worked with him at Dalton Care Home for three years. They consistently provided compassionate and professional care to our residents, including those with advanced dementia.",
          attachments: [
            {
              id: "46e59012-75a8-410e-857a-24e851f85894",
              file: "Nathan_DWC_Certificate.png",
              url: "https://safer-recruit.s3.amazonaws.com/reference_entries/Nathan_DWC_Certificate.png",
              file_size: 494614,
            },
          ],
          added_by: "0f7df761-3f94-4582-99fd-4da9ba45bb8a",
        },
        verification_logs: [
          {
            id: "299bccae-8dbd-45f7-ab82-8ff4f8f75a68",
            date_contacted: "24/10/2025 08:03AM",
            verification_notes:
              "Confirmed referee provided the reference. Unable to reach referee - follow-up required",
            additional_notes: "",
            verification_outcome: "Referee Verified but Reference Invalid",
            verified_by: "Safer Recruit",
          },
        ],
      },
      {
        id: "d92f6e74-e6df-4465-b34c-83db05fe7a43",
        is_for_latest_employment: true,
        referee_name: "Grant",
        company_name: "acme ltd.",
        referee_role: "Lead",
        referee_email: "grant@gmail.com",
        reference_type: "professional_reference",
        referee_phone_number: "+447748851882",
        is_reviewed: true,
        reviewed_by: "Safer Recruit",
        reviewed_at: "24/10/2025 07:11PM",
        reference_entry: {
          id: "fd27bb7c-119a-4a29-9610-6dd928de19df",
          date_received: "24/10/2025 09:35AM",
          notes: "Professional reference provided.",
          attachments: [
            {
              id: "02e8228d-259b-43a6-a244-d273ad90d1ff",
              file: "Nathan_DWC_Certificate.png",
              url: "https://safer-recruit.s3.amazonaws.com/reference_entries/Nathan_DWC_Certificate.png",
              file_size: 494614,
            },
          ],
          added_by: "0f7df761-3f94-4582-99fd-4da9ba45bb8a",
        },
        verification_logs: [
          {
            id: "7da89cd6-40ba-43d3-9c78-c98877254610",
            date_contacted: "24/10/2025 07:59AM",
            verification_notes:
              "Confirmed referee provided the reference. Spoke with referee and validated employment details",
            additional_notes: "",
            verification_outcome: "Referee and Reference Verified",
            verified_by: "Safer Recruit",
          },
        ],
      },
    ],
    dbs_information: {
      id: "abea9726-ba39-4d07-a162-294916899c4f",
      certificate_number: "001899138212",
      status: "clear_no_record",
      is_valid: true,
      result: {
        status: "BLANK_NO_NEW_INFO",
        last_name: "MCKOY",
        first_name: "JAMAAL",
        data_generated: "2024-10-15",
      },
      file_uploads: [],
      is_reviewed: true,
      reviewed_by: "Safer Recruit",
      reviewed_at: "24/10/2025 07:27PM",
    },
    onfido_results: [
      {
        id: "a86f2b60-362d-496e-a442-968a1cdec59b",
        reviewed_at: "24/10/2025 07:27PM",
        reviewed_by: "Safer Recruit",
        is_reviewed: true,
        verification_type: "identity_verification",
        first_name: "Brian",
        last_name: "Margret",
        expiry_date: "2031-05-28",
        issuing_date: "2018-08-16",
        document_type: "passport",
        document_number: "999999999",
        issuing_country: "GB",
        completed_at: "2025-10-24T19:25:01.973171Z",
        status: "approved",
        document_photos: [
          ["89e24b72-5405-4ff4-824d-c6c890b1c68e", "document_photo", "w3HbKACxwYbgMLurLIxuDrRBMraNN06HH0ki8/C+8QI="],
        ],
      },
    ],
  },
}
